spring.application.name=localproducersmarketplace

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/localproducersmarketplace
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.hikari.maximum-pool-size=10
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret=RQJJ0FU7aM+A7OVIEErAIBdebegP+mjt4HCE6bPqJQA=
jwt.expiration=86400000
