spring.application.name=localproducersmarketplace

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/localproducersmarketplace
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.hikari.maximum-pool-size=10
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
minio.url=http://localhost:9000
minio.bucket=lpm
minio.key=minio
minio.secret=minioadmin

jwt.secret=RQJJ0FU7aM+A7OVIEErAIBdebegP+mjt4HCE6bPqJQA=
jwt.expiration=86400000
